### ISSUE TITLE
能否提供下Hosts源，想要自动更新在路由器中

### ISSUE THREAD

**Issue by ghost** [Lerist/Go-Hosts#1]

**Comment by ghost** [comment]
https://github.com/sy618/hosts

**Comment by Cryolitia** [comment]
我写了一个shell脚本来自动在路由器中部署或更新hosts：https://github.com/singleNeuron/Go-Hosts

**Comment by singleNeuron** [comment]
我写了一个shell脚本来自动在路由器中部署或更新hosts：https://github.com/singleNeuron/Go-Hosts

**Comment by C4droid** [comment]
通过抓包，发现APP的hosts是用cdn托管，每次更新的文件也是根据日期和hash值区分。感觉作者并不想公开hosts

**Comment by Domado** [comment]
没错，我研究过

**Comment by Domado** [comment]
Go Hosts的hosts是用又拍云cdn经过post提交获取hosts文件地址的

**Comment by ghost** [comment]
https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts
